language: php

php:
  - 7.0

before_script:
    - travis_retry composer self-update
    - travis_retry composer install

notifications:
    on_success: never
    on_failure: always

script: vendor/bin/phpunit
